---
# ProxMox VE 완전 자동 설정 마스터 플레이북
# 모든 설정을 순서대로 실행합니다

- name: "🚀 ProxMox VE 완전 자동 설정"
  hosts: localhost
  gather_facts: no
  vars:
    playbook_dir: "{{ playbook_dir }}"
    
  tasks:
    - name: "설정 시작 안내"
      debug:
        msg: |
          ================================
          🚀 ProxMox VE 완전 자동 설정 시작
          ================================
          
          다음 순서로 설정을 진행합니다:
          1️⃣ SSH 키 기반 인증 설정
          2️⃣ 연결 테스트 및 확인  
          3️⃣ APT 저장소 설정
          4️⃣ Git 및 개발 도구 설치
          5️⃣ Docker & Docker Compose 설치
          6️⃣ Bash 환경 설정 및 커스터마이징
          7️⃣ Fail2ban 보안 설정
          
          ⏱️ 예상 소요시간: 12-20분
          ⚠️ 중간에 중단하지 마세요!
          ================================

    - name: "1️⃣ SSH 키 기반 인증 설정 실행"
      include: 01-setup-ssh-keys.yml

    - name: "2️⃣ 연결 테스트"
      shell: ansible proxmox-server -m ping
      register: connection_test
      delegate_to: localhost
      changed_when: false

    - name: "연결 테스트 결과"
      debug:
        msg: |
          {{ '✅ SSH 키 기반 연결 성공!' if connection_test.rc == 0 else '❌ 연결 실패!' }}
          
    - name: "연결 실패 시 중단"
      fail:
        msg: |
          ❌ SSH 키 기반 연결에 실패했습니다!
          이전 단계를 확인하고 다시 시도하세요.
      when: connection_test.rc != 0

    - name: "3️⃣ APT 저장소 설정 실행"
      include: 02-setup-proxmox-apt.yml

    - name: "4️⃣ Git 및 개발 도구 설치 실행"
      include: 03-install-devtools.yml

    - name: "5️⃣ Docker & Docker Compose 설치 실행"
      include: 04-install-docker-compose.yml

    - name: "6️⃣ Bash 환경 설정 및 커스터마이징 실행"
      include: 05-setup-bash-config.yml

    - name: "7️⃣ Fail2ban 보안 설정 실행"
      include: 06-setup-fail2ban.yml

    - name: "🎉 모든 설정 완료!"
      debug:
        msg: |
          ================================
          🎉 ProxMox VE 설정 완료!
          ================================
          
          ✅ 완료된 설정:
          • SSH 키 기반 인증 활성화
          • 패스워드 인증 비활성화 (보안 강화)
          • ProxMox APT 저장소 최적화
          • 무료 No-Subscription 저장소 활성화
          
          🌐 ProxMox 웹 관리:
          https://{{ hostvars[groups['proxmox'][0]]['ansible_host'] }}:8006
          
          📋 이제 가능한 작업:
          • SSH 키로 서버 접속
          • APT 패키지 관리 (업데이트/설치)
          • ProxMox 웹 인터페이스 사용
          • 가상머신 생성 및 관리
          
          🔧 추가 설정 권장사항:
          • 정기적인 시스템 업데이트 설정
          • 백업 전략 수립
          • 방화벽 설정 검토
          • SSL 인증서 설정 (필요시)
          
          ================================
